server:
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://106.15.177.101:3306/dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: dev
    password: fiHCYWBBJJpXR7Sc

  redis:
    database: 1
    host: 106.15.177.101
    password: yang25403
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: 10s

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: "/opt/work/${spring.application.name}"




