server:
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://106.15.177.101:3306/dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: dev
    password: fiHCYWBBJJpXR7Sc

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: "./log/${spring.application.name}"




